/**
 * Export Service
 * Handles downloads: .tex file, Overleaf project ZIP, PDF, and complete application package
 */

const AdmZip = require('adm-zip');
const { renderLatexResume } = require('./latexTemplateRenderer');
const { compileLatexToPdf } = require('./latexCompilerService');

/**
 * Creates a complete Overleaf project ZIP containing main.tex and project assets
 */
const createOverleafZip = (resumeData, templateId = 'template-01') => {
  const zip = new AdmZip();
  const latexSource = renderLatexResume(resumeData, templateId);

  // Add main.tex
  zip.addFile('main.tex', Buffer.from(latexSource, 'utf8'), 'Main LaTeX resume source');

  // Add README for Overleaf users
  const readmeContent = `# Overleaf / LaTeX ATS Resume Project
Generated by AI ATS Resume Builder & Intelligence Platform.

## How to use in Overleaf:
1. Upload this ZIP directly to Overleaf (New Project -> Upload Project).
2. Ensure compiler is set to pdfLaTeX or XeLaTeX in Project Settings.
3. Click "Recompile" to generate your high-fidelity ATS resume PDF.
`;
  zip.addFile('README.md', Buffer.from(readmeContent, 'utf8'));

  return zip.toBuffer();
};

/**
 * Creates a complete Application Package ZIP
 * (resume.pdf, resume.tex, overleaf-project.zip, cover-letter.txt)
 */
const createApplicationPackageZip = async (resumeData, coverLetterText = '', templateId = 'template-01') => {
  const zip = new AdmZip();
  const latexSource = renderLatexResume(resumeData, templateId);
  const { pdfBuffer } = await compileLatexToPdf(latexSource, resumeData, templateId);
  const overleafZipBuffer = createOverleafZip(resumeData, templateId);

  zip.addFile('resume.pdf', pdfBuffer);
  zip.addFile('resume.tex', Buffer.from(latexSource, 'utf8'));
  zip.addFile('overleaf-project.zip', overleafZipBuffer);

  if (coverLetterText) {
    zip.addFile('cover-letter.txt', Buffer.from(coverLetterText, 'utf8'));
  }

  const manifest = JSON.stringify(
    {
      candidate: resumeData.personal?.fullName || 'Candidate',
      targetRole: resumeData.targetRole || 'Software Engineer',
      generatedAt: new Date().toISOString(),
      platform: 'AI ATS Resume Builder & Intelligence Platform',
    },
    null,
    2
  );
  zip.addFile('manifest.json', Buffer.from(manifest, 'utf8'));

  return zip.toBuffer();
};

module.exports = {
  createOverleafZip,
  createApplicationPackageZip,
};
